(fix) change the location of the termination-log
overmindtech/aws-source pull request #609
Opened 2024-09-05 09:03 UTC by tphoney

We change the default user in the dockerfile, which has no access to /dev. we can set an arbitary path for kubernetes to pick up our log eg https://kubernetes.io/docs/tasks/debug/debug-application/determine-reason-pod-failure/#:~:text=Kubernetes%20retrieves%20termination%20messages%20from,to%20use%20a%20different%20file.

2024-09-05 09:07 UTC, tphoney commented
obviously /exit, is a horrible name for a folder, but we need to decide

- if we want keep writing to the default place, we need to change the default user in the dockerfile
- we change the user we run pods as in kubernetes, so it has permissions, NB OpenShift Kubernetes uses a range of unique user IDs for each project, which can appear to be random user IDs, so this may not work in longer term
- we follow this approach and specify a folder for the termination logs, and check a different place with kubernetes https://kubernetes.io/docs/tasks/debug/debug-application/determine-reason-pod-failure/#:~:text=Kubernetes%20retrieves%20termination%20messages%20from,to%20use%20a%20different%20file

2024-09-05 12:57 UTC, dylanratcliffe requested changes
I like the idea of just writing it to a location we control, but I do agree that `/exit` isn't a good name. Do these containers have any kind of a default log directory we could use like `/log` or `/var/log`?

2024-09-05 13:30 UTC, tphoney commented
> I like the idea of just writing it to a location we control, but I do agree that `/exit` isn't a good name. Do these containers have any kind of a default log directory we could use like `/log` or `/var/log`?

I'll check permissions and see what makes sense.

2024-09-05 18:53 UTC, dylanratcliffe approved these changes

2024-09-10 14:33 UTC, DavidS-ovm approved these changes

2024-09-10 14:34 UTC, merged